//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webplantas.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class proceso
    {
        public int idProceso { get; set; }
        public int idUsuario { get; set; }
        public string clima { get; set; }
        public decimal temperatura { get; set; }
        public decimal humedad { get; set; }
        public System.DateTime fechaProceso { get; set; }
        public string lugar { get; set; }
        public Nullable<System.TimeSpan> tiempo_de_riego { get; set; }
        public string sector_de_riego { get; set; }
        public Nullable<int> calculo_de_agua { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
